app:
  port: 8080
database:
  driver: mysql
  source: 129.204.200.248
  port: 3306
  user: spider-go_dev
  pass: 18608459749fd
  name: spider-go_dev
redis:
  # 会话缓存数据库
  session:
    host: 129.204.200.248:6379
    pass: redis_RZpfr5
    db: 0
  # 验证码数据库
  captcha:
    host: 129.204.200.248:6379
    pass: redis_RZpfr5
    db: 1
jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  issuer: "spider-go"
jwc:
  login_url: "https://authserver.csuft.edu.cn/authserver/login?service=http%3A%2F%2Fjwgl.csuft.edu.cn%2F"
  course_url: "http://jwgl.csuft.edu.cn/jsxsd/xskb/xskb_list.do"
  grade_url: "http://jwgl.csuft.edu.cn/jsxsd/kscj/cjcx_list"
  grade_level_url: "http://jwgl.csuft.edu.cn/jsxsd/kscj/djkscj_list"
  exam_url: "http://jwgl.csuft.edu.cn/jsxsd/xsks/xsksap_list"
  captcha_url: "https://authserver.csuft.edu.cn/authserver/needCaptcha.html?"
  captcha_image_url: "https://authserver.csuft.edu.cn/authserver/captcha.html?"
email:
  # SMTP 邮件服务器配置
  smtp_host: "smtp.qq.com"          # QQ邮箱
  smtp_port: 465
  username: "1628615876@qq.com"     # 发件人邮箱
  password: "kwxuotnueozvdjeb"    # SMTP 授权码（不是邮箱密码）
  from_name: "Spider-Go 验证码"      # 发件人名称
ocr:
  host: "http://139.196.168.236:8000/ocr"