app:
  port: 8080
database:
  driver: mysql
  source: 129.204.200.248
  port: 3306
  user: spider-go_dev
  pass: 18608459749fd
  name: spider-go_dev
redis:
  host: 129.204.200.248:6379
  pass: redis_RZpfr5
  db: 0
aliyun:
  api_key:
  secret:
